# -*- coding: utf-8 -*-

from .testproblem import TestProblem
from .cifar10_3c3d import cifar10_3c3d
from .cifar10_vgg16 import cifar10_vgg16
from .cifar10_vgg19 import cifar10_vgg19
from .cifar100_3c3d import cifar100_3c3d
from .cifar100_allcnnc import cifar100_allcnnc
from .cifar100_vgg16 import cifar100_vgg16
from .cifar100_vgg19 import cifar100_vgg19
from .cifar100_wrn404 import cifar100_wrn404
from .fmnist_2c2d import fmnist_2c2d
from .fmnist_logreg import fmnist_logreg
from .fmnist_mlp import fmnist_mlp
from .fmnist_vae import fmnist_vae
from .imagenet_inception_v3 import imagenet_inception_v3
from .imagenet_vgg16 import imagenet_vgg16
from .imagenet_vgg19 import imagenet_vgg19
from .mnist_2c2d import mnist_2c2d
from .mnist_logreg import mnist_logreg
from .mnist_mlp import mnist_mlp
from .mnist_vae import mnist_vae
from .quadratic_deep import quadratic_deep
from .svhn_3c3d import svhn_3c3d
from .svhn_wrn164 import svhn_wrn164
from .tolstoi_char_rnn import tolstoi_char_rnn
from .two_d_beale import two_d_beale
from .two_d_branin import two_d_branin
from .two_d_rosenbrock import two_d_rosenbrock
